spring:
  application:
     name: accounts-service
  jpa:
     hibernate:
        ddl-auto: update
security:
  basic:
    enabled: false
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${server.port:8080}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.service-registry.credentials.uri:http://127.0.0.1:8762}/eureka/
