spring:
  application:
     name: web-service
eureka:
  client:
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
pivotal:
  summary:
    quotes: 3
    symbols:
      it: EMC,ORCL,IBM,INTC,AMD
      fs: JPM,C,MS,BAC,GS,WFC,BK
